url: "https://profemilfreme.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/DisruptiveArchitectures" # the subpath of your site, e.g. /blog
title: "Disruptive Architectures" # the name of your site, e.g. ACME Corp.

permalink: /:year/:month/:title:output_ext

plugins: [jekyll-paginate, jekyll-toc]
paginate: 5
paginate_path: /page:num/

collections:
  classes:
    sort_by: class
    output: true

exclude: [.obsidian/]


defaults:
  - 
    scope:
      path: "_classes"
    values:
      toc: true
